### PR TITLE
Fix guide only showing lang keys

### PR DESCRIPTION
**Pull request by pupnewfster**
Changes the guide lang file to use all lowercase for lang keys. This fixes them not matching the lang keys the guide book is trying to use, and makes the guide book readable.

### CODE REVIEW

**Comment by Arcaratus** [comment]
Can you do this for all the lang files?

**Comment by pupnewfster** [comment]
I did it for the only two lang files in that the guide has. If you mean for the normal lang files, I believe all the entries work properly. Unless you are asking me to convert them to being lowercase (as they probably should be) and then changing the code references to also use lowercase instead of having things like `itemGroup.bloodarsenal.creativeTab`

**Comment by Arcaratus** [comment]
Yep, meant the second one

**Comment by pupnewfster** [comment]
Ok, I should be able to do that

**Comment by pupnewfster** [comment]
While I am at it I will also make it use the resource pack format 3, which should be used for 1.11 and 1.12, and requires lower cased file names in the resources folder.

**Comment by pupnewfster** [comment]
@Arcaratus The other lang files are updated, and it is all using resource pack format 3 now instead of the legacy support for format 2. The majority of lang keys in ja_JP and zh_CN were incorrect, so I changed the keys so that the translation points to the correct items.

**Comment by Arcaratus** [comment]
Thanks a lot!

**Comment by pupnewfster** [comment]
No problem, just trying to get a bunch of stuff more "polished" given the mid game of my pack requires the extensive use of refined life essence, so the more things that get fixed the more likely it is that you will do a release sooner rather than later. So let me know if there is anything else that I can help with to speed up the process.

**Pull request merged**
